# Generated by Django 5.2.8 on 2025-11-10 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2025), django.core.validators.MinValueValidator(1900)])),
                ('description', models.TextField(blank=True, default=';)')),
            ],
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(5)])),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='somm.car')),
            ],
        ),
    ]
