# Generated by Django 5.2.8 on 2025-11-10 19:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)])),
                ('music_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=';{')),
            ],
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='license_plate',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='Nice song ;)')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somm.album')),
            ],
        ),
    ]
