# Generated by Django 5.2.8 on 2025-11-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somm', '0002_album_alter_licenseplate_license_plate_songs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
