# Generated by Django 5.2.8 on 2025-11-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somm', '0004_team_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
